services:
  backend:
    image: docker_demo-backend
    container_name: docker_demo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
  
  frontend:
    image: docker_demo-frontend
    pull_policy: never
    container_name: docker_demo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80


  mongodb:
    image: mongo:7.0.20
    container_name: docker_demo-mongodb
    volumes:
      - ./mongodb-data:/data/db
    env_file:
      - ./mongodb/.env

  mongo-express:
    image: mongo-express:1.0.2
    container_name: docker_demo-mongo-express
    ports:
      - 8081:8081
    env_file:
      - ./mongo-express/.env
    depends_on:
      - mongodb
      
volumes:
  mongodb-data: